apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-models
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/oginskis/.ollama"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-models
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: local-models